### ISSUE TITLE
Spaces in foreach

### ISSUE THREAD

**Issue by MohamedChaabouni** [jesusvlo/XML2ESCPOS#1]
Hello, 

If you still maintain this package.  

For the foreach section spaces are ignored. Why ? and how to fix this please.

Thanks.

**Comment by MohamedChaabouni** [comment]
Got it done with Tabs but can you explain more the tab function please?

**Comment by jesusvlo** [comment]
Hello Mohamed,

About tabs, one example, (Ignore the numbers, I have only put them to make the example clearer):

<DEFTABS N1='5' N2='12' />
Ab<TAB>Cd<TAB>Ef

0123456678901234567890

Result:
Ab       Cd             Ef
